[build] change jdk11 to jdk8 (#80)
After introducing hadoop in thirdparty, we need to use jdk8 to compile it.
If using jdk11 and run BE using jdk8, it will return error: 

`NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;`